version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=rpg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Licam@616174
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
